package org.firstinspires.ftc.teamcode.brainstemPilotAuto.opmodeAutos;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import org.firstinspires.ftc.teamcode.brainstemPilotAuto.PilotAutoBase;

/**
 * AUTO-GENERATED by Brainstem Pilot UI — do not edit manually.
 * Variant: Example Variant Auto
 */
@Autonomous(name = "Example Variant Auto", group = "Pilot")
public class ExampleVariantAuto extends PilotAutoBase {
    public ExampleVariantAuto() {
        super("Example_Variant_Auto");
    }
}
