package org.firstinspires.ftc.teamcode.brainstemPilotAuto.opmodeAutos;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import org.firstinspires.ftc.teamcode.brainstemPilotAuto.PilotAutoBase;

/**
 * AUTO-GENERATED by Brainstem Pilot UI — do not edit manually.
 * Variant: Example Auto
 */
@Autonomous(name = "Example Auto", group = "Pilot")
public class ExampleAuto extends PilotAutoBase {
    public ExampleAuto() {
        super("Example_Auto");
    }
}
